/// Generated by AssetsRefGenerator on 2022/04/24
class Res {
  static const String background_image = "assets/images/background_image.png";
  static const String globus = "assets/globus.png";
  static const String ic_cloude = "assets/icons/ic_cloude.png";
  static const String ic_lighting = "assets/icons/ic_lighting.png";
  static const String ic_rain_snow = "assets/icons/ic_rain_snow.png";
  static const String ic_thunder = "assets/icons/ic_thunder.png";
  static const String ic_wint = "assets/icons/ic_wint.png";
  static const String icon_rain = "assets/icons/icon_rain.png";
  static const String im_sky = "assets/im_sky.png";
  static const String image_ellipse = "assets/images/image_ellipse.png";
  static const String img = "assets/img.png";
  static const String img_1 = "assets/images/img_1.png";
  static const String Manrope_Regular = "assets/font/Manrope-Regular.ttf";
  static const String splash = "assets/splash.png";
}
